Databases:
  # tell pyannote.database where to find AMI wav files.
  # {uri} is a placeholder for the session name (eg. ES2004c).
  # you might need to update this line to fit your own setup.

  DISPLACE: wav/{uri}.wav

Protocols:

  DISPLACE:
    SpeakerDiarization:
      mini:
        train:
          uri: ../lists/train_displace.txt
          annotation: ../only_words/rttms/train/{uri}.rttm
          annotated: ../uems/train/{uri}.uem
        development:
          uri: ../lists/dev_displace.txt
          annotation: ../only_words/rttms/dev/{uri}.rttm
          annotated: ../uems/dev/{uri}.uem
        test:
          uri: ../lists/test_displace.txt
          annotation: ../only_words/rttms/test/{uri}.rttm
          annotated: ../uems/test/{uri}.uem


